import Head from "next/head";
import Banner from "../components/Banner";

export default function Home() {
	function handleBannerBtnClick() {
		console.log("hey!");
	}

	return (
		<div className="py-0 px-8">
			<Head>
				<title>Coffee Connoisseur</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="flex flex-1 flex-col justify-center items-center py-16 px-0 min-h-screen">
				<Banner
					buttonText="View stores nearby"
					onButtonClick={handleBannerBtnClick}
				/>
			</main>
		</div>
	);
}
