import Head from "next/head";
import Image from "next/image";

import Banner from "../components/Banner";
import Card from "../components/Card";

import { getCoffeeStores } from "../lib/coffee-stores";

import type { GetStaticProps, InferGetStaticPropsType } from "next";
import type { CoffeeStoreData } from "../lib/coffee-stores";

export const getStaticProps: GetStaticProps<{
	coffeeStores: CoffeeStoreData[];
}> = async (context) => {
	const coffeeStores = await getCoffeeStores({
		lat: 14.581850805315819,
		lng: 120.97703241286848,
	});

	return {
		props: {
			coffeeStores,
		},
	};
};

export default function Home(
	props: InferGetStaticPropsType<typeof getStaticProps>
) {
	function handleBannerBtnClick() {
		console.log("hey!");
	}

	return (
		<div className="mb-56 sm:px-4 md:px-10 lg:px-10">
			<Head>
				<title>Coffee Connoisseur</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="mx-auto mt-10 max-w-6xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
				<Banner
					buttonText="View stores nearby"
					onButtonClick={handleBannerBtnClick}
				/>
				<div className="absolute top-0 z-10 md:right-[20%] lg:right-[20%]">
					<Image
						src="/static/hero-image.png"
						alt=""
						width={700}
						height={400}
						className="h-[400px] w-[700px]"
					/>
				</div>

				{props.coffeeStores.length > 0 ? (
					<>
						<h2 className="mt-8 pb-8 text-4xl font-bold text-white-100">
							Toronto Stores
						</h2>
						<div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3">
							{props.coffeeStores.map((coffeeStore) => (
								<Card
									key={coffeeStore.id}
									name={coffeeStore.name}
									href={`/coffee-store/${coffeeStore.id}`}
									imgUrl={
										coffeeStore.imgUrl ??
										"https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
									}
									imgAlt={coffeeStore.name}
								/>
							))}
						</div>
					</>
				) : null}
			</main>
		</div>
	);
}
