import Head from "next/head";
import Image from "next/image";

import Banner from "../components/Banner";
import Card from "../components/Card";

import type { GetStaticProps, InferGetStaticPropsType } from "next";

import coffeeStoresData from "../data/coffee-stores.json";

export const getStaticProps: GetStaticProps<{
	coffeeStores: typeof coffeeStoresData;
}> = (context) => {
	return {
		props: {
			coffeeStores: coffeeStoresData,
		},
	};
};

export default function Home(
	props: InferGetStaticPropsType<typeof getStaticProps>
) {
	function handleBannerBtnClick() {
		console.log("hey!");
	}

	return (
		<div className="mb-56 sm:px-4 md:px-10 lg:px-10">
			<Head>
				<title>Coffee Connoisseur</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="max-w-6xl mt-10 mx-auto px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
				<Banner
					buttonText="View stores nearby"
					onButtonClick={handleBannerBtnClick}
				/>
				<div className="absolute top-0 z-10 md:right-[20%] lg:right-[20%]">
					<Image
						src="/static/hero-image.png"
						alt=""
						width={700}
						height={400}
						className="w-[700px] h-[400px]"
					/>
				</div>

				{props.coffeeStores.length > 0 ? (
					<>
						<h2 className="mt-8 pb-8 text-4xl text-white-100 font-bold">
							Toronto Stores
						</h2>
						<div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3">
							{props.coffeeStores.map((coffeeStore) => (
								<Card
									key={coffeeStore.id}
									name={coffeeStore.name}
									href={`/coffee-store/${coffeeStore.id}`}
									imgUrl={coffeeStore.imgUrl}
									imgAlt={coffeeStore.name}
								/>
							))}
						</div>
					</>
				) : null}
			</main>
		</div>
	);
}
